name: Package fonts and upload to release

on: 
  release:
    # do not run when created/draft, only when finalised
    types: [published]

jobs:
  release:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Zip LXGWBrightCode
        uses: edgarrc/action-7z@v1
        with:
          args: 7z a -t7z -mx=9 LxgwBrightCode.7z LxgwBrightCode/*.ttf

      - name: Zip LXGWBrightCodeGB
        uses: edgarrc/action-7z@v1
        with:
          args: 7z a -t7z -mx=9 LxgwBrightCodeGB.7z LxgwBrightCodeGB/*.ttf

      - name: Zip LXGWBrightCodeTC
        uses: edgarrc/action-7z@v1
        with:
          args: 7z a -t7z -mx=9 LxgwBrightCodeTC.7z LxgwBrightCodeTC/*.ttf
        
      # upload files to releases
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: ./*.7z
          tag: ${{ github.ref }}
          overwrite: true